# Generated by Django 3.2.5 on 2021-08-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magicshop', '0002_alter_ingredient_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=100)),
                ('pentacles', models.CharField(choices=[('⛥', '1'), ('⛥⛥', '2'), ('⛥⛥⛥', '3'), ('⛥⛥⛥⛥', '4'), ('⛥⛥⛥⛥⛥', '5')], default='⛥⛥⛥', max_length=5)),
                ('review', models.CharField(max_length=400)),
            ],
        ),
    ]
